You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"

 

Constraints:

1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.


SOLUTION:::
class Solution {
    public String generateString(String s1, String s2) {
        int n = s1.length();
        int m = s2.length();
        int l = n + m - 1;
        char[] r = new char[l];
        boolean[] f = new boolean[l];

        for (int i = 0; i < n; i++) {
            if (s1.charAt(i) == 'T') {
                for (int j = 0; j < m; j++) {
                    if (f[i + j] && r[i + j] != s2.charAt(j)) {
                        return "";
                    }
                    r[i + j] = s2.charAt(j);
                    f[i + j] = true;
                }
            }
        }

        for (int i = 0; i < l; i++) {
            if (!f[i]) {
                r[i] = 'a';
            }
        }

        for (int i = 0; i < n; i++) {
            if (s1.charAt(i) == 'F') {
                if (match(r, i, s2)) {
                    boolean ok = false;
                    for (int j = m - 1; j >= 0; j--) {
                        if (!f[i + j]) {
                            r[i + j] = 'b';
                            ok = true;
                            break; 
                        }
                    }
                    if (!ok) return "";
                }
            }
        }

        return new String(r);
    }

    private boolean match(char[] r, int s, String s2) {
        for (int j = 0; j < s2.length(); j++) {
            if (r[s + j] != s2.charAt(j)) return false;
        }
        return true;
    }
}
